# Generated by Django 4.2.30 on 2026-05-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus_active', models.BooleanField(default=True)),
                ('firewall_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_status', to='agents.machine')),
            ],
            options={
                'verbose_name': 'Status de Segurança',
                'verbose_name_plural': 'Status de Segurança',
            },
        ),
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='agents.machine')),
            ],
            options={
                'verbose_name': 'Software Instalado',
                'verbose_name_plural': 'Softwares Instalados',
                'unique_together': {('machine', 'name')},
            },
        ),
    ]
