# Generated by Django 4.2.30 on 2026-05-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_limit', models.FloatField(default=95.0, verbose_name='Limite de CPU (%)')),
                ('ram_limit', models.FloatField(default=90.0, verbose_name='Limite de RAM (%)')),
                ('disk_limit', models.FloatField(default=80.0, verbose_name='Limite de Disco (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_threshold', to='companies.company')),
            ],
            options={
                'verbose_name': 'Limites de Monitoramento',
                'verbose_name_plural': 'Limites de Monitoramento',
            },
        ),
    ]
