# Generated by Django 4.2.30 on 2026-05-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('ram_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('collected_at', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.machine')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-collected_at'],
            },
        ),
    ]
