# Generated by Django 4.2.30 on 2026-05-28 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(max_length=200)),
                ('cpu_model', models.CharField(max_length=200)),
                ('cpu_cores', models.IntegerField()),
                ('ram_total_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Alerta Médio'), ('critical', 'Crítico')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='companies.company')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
    ]
