# Generated by Django 4.2.30 on 2026-05-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='disk_details',
            field=models.TextField(blank=True, default='', verbose_name='Detalhes do Disco'),
        ),
        migrations.AddField(
            model_name='machine',
            name='ram_details',
            field=models.TextField(blank=True, default='', verbose_name='Detalhes da Memória'),
        ),
    ]
