# Generated by Django 4.2.30 on 2026-06-15 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_mfa_enforced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação Executada')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho / URL')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Método HTTP')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes da Requisição (Body/Params)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company', verbose_name='Tenant')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Log de Auditoria Global',
                'verbose_name_plural': 'Logs de Auditoria Globais',
                'ordering': ['-created_at'],
            },
        ),
    ]
