# Generated by Django 4.2.30 on 2026-05-30 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lgpd_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite LGPD'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Aceitou Termos LGPD'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_terms_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Versão dos Termos'),
        ),
        migrations.CreateModel(
            name='LGPDAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_email', models.CharField(max_length=255, verbose_name='E-mail do Titular')),
                ('action', models.CharField(choices=[('consent_accept', 'Aceite dos Termos de Uso/Privacidade'), ('data_export', 'Exportação de Dados Pessoais (Portabilidade)'), ('anonymization', 'Anonimização de Conta (Exclusão/Esquecimento)'), ('role_change', 'Alteração de Nível de Acesso'), ('user_creation', 'Criação de Usuário'), ('user_update', 'Alteração de Cadastro de Usuário')], max_length=50, verbose_name='Operação de Tratamento')),
                ('details', models.TextField(verbose_name='Detalhes da Operação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lgpd_logs', to='companies.company', verbose_name='Empresa')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lgpd_actions_done', to=settings.AUTH_USER_MODEL, verbose_name='Operador (DPO/Admin)')),
            ],
            options={
                'verbose_name': 'Log de Auditoria LGPD',
                'verbose_name_plural': 'Logs de Auditoria LGPD',
                'ordering': ['-created_at'],
            },
        ),
    ]
