# Generated by Django 4.2.30 on 2026-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lgpd_accepted_at_user_lgpd_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA Ativado'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Segredo MFA (TOTP)'),
        ),
    ]
