# Generated by Django 4.2.30 on 2026-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
