# Generated by Django 4.2.30 on 2026-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_address_city_company_address_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotipo'),
        ),
    ]
