# Generated by Django 4.2.30 on 2026-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mfa_enforced',
            field=models.BooleanField(default=False, verbose_name='MFA Obrigatório para Usuários'),
        ),
    ]
