# Generated by Django 4.2.30 on 2026-05-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('anthropic', 'Anthropic (Claude 3.5 Sonnet / Claude 3 Haiku)'), ('google', 'Google Gemini (1.5 Pro / Flash)')], default='openai', max_length=50)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('api_key_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'Configuração de IA',
                'verbose_name_plural': 'Configurações de IA',
            },
        ),
    ]
