# Generated by Django 4.2.30 on 2026-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('openrouter', 'OpenRouter (OpenAI-compatible)'), ('anthropic', 'Anthropic (Claude 3.5 Sonnet / Claude 3 Haiku)'), ('google', 'Google Gemini (1.5 Pro / Flash)')], default='openai', max_length=50),
        ),
    ]
