# Generated by Django 4.2.30 on 2026-05-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TicketWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apontamento de Chamado',
                'verbose_name_plural': 'Apontamentos de Chamado',
                'ordering': ['-started_at'],
            },
        ),
    ]
