# Generated by Django 4.2.30 on 2026-05-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('tickets', '0002_ticket_ai_report_ticket_ai_report_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='agents.machine'),
        ),
    ]
