# Generated by Django 4.2.30 on 2026-06-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_mfa_enforced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, verbose_name='Artigo/Inciso (CNJ 213)')),
                ('description', models.TextField(verbose_name='Descrição do Requisito')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obrigatório')),
            ],
            options={
                'verbose_name': 'Requisito de Conformidade',
                'verbose_name_plural': 'Requisitos de Conformidade',
                'ordering': ['article'],
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Risco Identificado')),
                ('impact', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20, verbose_name='Impacto')),
                ('probability', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20, verbose_name='Probabilidade')),
                ('mitigation_plan', models.TextField(blank=True, verbose_name='Plano de Tratamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, verbose_name='Risco Tratado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Matriz de Risco',
                'verbose_name_plural': 'Matrizes de Risco',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('implemented', 'Implementado'), ('partial', 'Parcial'), ('none', 'Não Implementado')], default='none', max_length=20, verbose_name='Status de Adequação')),
                ('evidence_text', models.TextField(blank=True, verbose_name='Evidência (Texto/Link)')),
                ('action_needed', models.TextField(blank=True, verbose_name='Ação Necessária')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='companies.company', verbose_name='Empresa')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance.compliancerequirement', verbose_name='Requisito CNJ 213')),
            ],
            options={
                'verbose_name': 'Evidência de Conformidade',
                'verbose_name_plural': 'Evidências de Conformidade',
                'unique_together': {('company', 'requirement')},
            },
        ),
    ]
